"""Canonical NexSolve data contracts and deterministic builders."""

from .schemas import (
    CaptureQuality,
    FlowRecord,
    ModelCompatibilityError,
    NetworkStateCompatibility,
    PacketRecord,
    Provenance,
    TemporalWindow,
    build_flows,
    build_temporal_windows,
    model_compatibility_report,
    temporal_windows_to_network_states,
)
from .state import (
    FeatureAvailability,
    FeatureSpec,
    HistoryResult,
    ModelCompatibilityReport,
    NetworkStateCandidate,
    build_network_state_candidates,
    build_state_history,
    candidates_to_network_states,
    evaluate_model_compatibility,
    feature_registry,
)

__all__ = [
    "CaptureQuality",
    "FlowRecord",
    "ModelCompatibilityError",
    "NetworkStateCompatibility",
    "PacketRecord",
    "Provenance",
    "TemporalWindow",
    "build_flows",
    "build_temporal_windows",
    "model_compatibility_report",
    "temporal_windows_to_network_states",
    "FeatureAvailability",
    "FeatureSpec",
    "HistoryResult",
    "ModelCompatibilityReport",
    "NetworkStateCandidate",
    "build_network_state_candidates",
    "build_state_history",
    "candidates_to_network_states",
    "evaluate_model_compatibility",
    "feature_registry",
    "MAX_UPLOAD_BYTES",
    "MAX_PCAP_UPLOAD_BYTES",
    "MAX_PCAP_UPLOAD_SIZE",
    "MAX_PACKETS",
    "MAX_FLOWS",
    "MAX_TEMPORAL_WINDOWS",
    "MAX_PROCESSING_DURATION_SECONDS",
    "MAX_CONCURRENT_JOBS",
    "MAX_REPORT_SIZE_BYTES",
    "ALLOWED_EXTENSIONS",
    "PCAP_MAGICS",
    "ResourceLimitExceededError",
    "ResourceLimitDetails",
    "sanitize_filename",
    "sanitize_error_message",
    "ERROR_DESCRIPTIONS",
    "get_user_friendly_error",
    "get_process_memory_mb",
    "PipelineMemoryTracker",
    "StageMemoryRecord",
]

from .config import (
    ALLOWED_EXTENSIONS,
    ERROR_DESCRIPTIONS,
    MAX_CONCURRENT_JOBS,
    MAX_FLOWS,
    MAX_PACKETS,
    MAX_PCAP_UPLOAD_BYTES,
    MAX_PCAP_UPLOAD_SIZE,
    MAX_PROCESSING_DURATION_SECONDS,
    MAX_REPORT_SIZE_BYTES,
    MAX_TEMPORAL_WINDOWS,
    MAX_UPLOAD_BYTES,
    PCAP_MAGICS,
    PipelineMemoryTracker,
    ResourceLimitDetails,
    ResourceLimitExceededError,
    StageMemoryRecord,
    get_process_memory_mb,
    get_user_friendly_error,
    sanitize_error_message,
    sanitize_filename,
)

