"""Generate evidence-based master implementation reports without retraining."""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
MODEL = ROOT / "models" / "nexsolve_world_model"
CIC = ROOT / "CIC-IDS2017" / "MachineLearningCSV" / "MachineLearningCVE"


def load(name: str) -> dict:
    return json.loads((REPORTS / name).read_text(encoding="utf-8"))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json(name: str, value: object) -> None:
    (REPORTS / name).write_text(json.dumps(value, indent=2, ensure_ascii=True), encoding="utf-8")


def write_md(name: str, text: str) -> None:
    (REPORTS / name).write_text(text.rstrip() + "\n", encoding="utf-8")


def main() -> None:
    config = load_model_json("config.json")
    schema = load_model_json("feature_schema.json")
    metadata = load_model_json("metadata.json")
    evaluation = load("world_model_evaluation.json")
    expanded = load("unsw_forecast_expanded_evaluation.json")
    flow_audit = load("cic_ids2017_flow_audit.json")
    progression = load("attack_progression_intelligence.json")
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    pcaps = sorted([str(path.relative_to(ROOT)).replace("\\", "/") for path in ROOT.rglob("*.pcap")]) + sorted([str(path.relative_to(ROOT)).replace("\\", "/") for path in ROOT.rglob("*.pcapng")])
    model_hashes = {path.name: {"size_bytes": path.stat().st_size, "sha256": sha256(path)} for path in sorted(MODEL.iterdir()) if path.is_file() and path.suffix in {".json", ".npz"}}
    cic_hashes = {path.name: {"size_bytes": path.stat().st_size, "sha256": sha256(path)} for path in sorted(CIC.glob("*.csv"))}
    status_before = f"""# NexSolve Master Implementation Status Before\n\nAudit timestamp (UTC): `{now}`\n\n## Scope\n\nResearch workspace: `{ROOT}`. Production repository was not modified. The active model package and trained weights were protected.\n\n## Working Components\n\n- Deterministic dataset audits and CIC-IDS2017 flow adapter.\n- UNSW-NB15 60-second temporal aggregation and chronological split.\n- Persistence, empirical-transition, and CIC static Logistic Regression baselines.\n- NumPy LSTM World Model with 46 inputs, lookback 8, and recursive T+1 through T+5 rollout.\n- Local FastAPI `/health` and `/forecast` service.\n- Local MITRE ATT&CK STIX bundle loading and contextual T1046 validation.\n- Research-side attack progression, trend, evidence, abstention, and defender guidance layer.\n\n## Incomplete Or Experimental\n\n- No local PCAP or PCAPNG exists; packet extraction and packet/flow alignment are blocked.\n- CIC flow CSVs have no timestamps, so CIC chronological training is blocked.\n- Current World Model is a research prototype trained on UNSW-NB15.\n- Only one eligible mixed-state future episode supports the expanded UNSW forecast evaluation.\n- Probability calibration, production model connection, and production end-to-end demo are not validated.\n\n## Current Contract\n\n- Feature count: `{len(schema['flow_features']) + len(schema['packet_features']) + len(schema['temporal_features'])}`.\n- Groups: `{len(schema['flow_features'])}` flow, `{len(schema['packet_features'])}` packet-interface, `{len(schema['temporal_features'])}` temporal.\n- Window: `{config['window_seconds']}` seconds; lookback `{config['lookback']}`; horizon `{config['forecast_horizon']}`.\n- Packet fields are explicit unavailable placeholders, not fabricated observations.\n- Labels are targets/metadata only and are excluded from encoded state.\n\n## Production Status\n\nProduction integration remains outside this research task and was not changed. Existing production wiring is optional and does not establish a validated connection to this research model.\n\n## Evidence\n\nSee `world_model_evaluation.json`, `unsw_forecast_expanded_evaluation.json`, `cic_ids2017_flow_audit.json`, and `attack_progression_intelligence.json`.\n"""
    write_md("nexsolve_master_implementation_status_before.md", status_before)
    pcap_json = {"generated_at_utc": now, "search_root": str(ROOT), "pcap_files": pcaps, "packet_extraction_performed": False, "status": "BLOCKED", "finding": "No .pcap or .pcapng file exists in the research workspace.", "dependent_phases": ["packet feature extraction", "flow-packet alignment", "packet compliance", "PCAP-based temporal episode validation"], "next_acquisition": "Official scenario-matched CIC-IDS2017 PCAP, beginning with Friday-WorkingHours-Afternoon-PortScan.pcap", "privacy": "No raw payloads were read or stored."}
    write_json("cic_ids2017_pcap_status.json", pcap_json)
    write_md("cic_ids2017_pcap_status.md", f"""# CIC-IDS2017 PCAP Status\n\nAudit timestamp (UTC): `{now}`\n\n## Result\n\n**BLOCKED**: no `.pcap` or `.pcapng` file exists under the research workspace. Packet extraction was not performed. No packet counts, timestamps, link-layer, protocol, or IP-version claims are available.\n\nThe flow CSVs are not substitutes for PCAP observations. Acquire the official scenario-matched capture, beginning with Friday afternoon PortScan, before extracting TTL, TCP windows, fragmentation, payload sizes, retransmissions, packet timing, or scan signatures.\n\nNo raw payloads were read or stored.\n""")
    provenance = []
    for group, names in schema.items():
        for name in names:
            source = "flow aggregate" if group == "flow_features" else "unavailable packet observation placeholder" if group == "packet_features" else "derived from chronological window states"
            provenance.append({"name": name, "group": group, "source": source, "type": "float64", "aggregation": "verified in existing model contract; see world_model.py", "units": "dataset/model-contract units", "available_at_time_t": group != "packet_features" or False, "causal_at_time_t": group == "temporal_features", "future_leak_risk": "excluded from state targets; preprocessing fitted on train only"})
    final_schema = {"title": "NexSolve final network state contract", "status": "PARTIALLY_DONE", "state": "S_t = [flow_features_t, packet_features_t, temporal_features_t]", "attack_label_in_state": False, "future_labels_in_state": False, "mitre_labels_in_state": False, "window_seconds": config["window_seconds"], "lookback": config["lookback"], "forecast_horizon": config["forecast_horizon"], "feature_count": len(provenance), "provenance": provenance, "packet_blocker": "No PCAP is available; packet group remains unavailable.", "flow_cic_blocker": "CIC flow CSVs have no event timestamp, IP, source port, or protocol."}
    write_json("final_network_state_schema.json", final_schema)
    write_md("final_network_state_schema.md", "# Final Network State Schema\n\nThe protected research contract is `S_t = [flow_features_t, packet_features_t, temporal_features_t]` with 46 numeric inputs, 60-second windows, lookback 8, and forecast horizon 5. Attack labels, future labels, and MITRE labels are not part of the encoded state.\n\nThe machine-readable provenance table is in `final_network_state_schema.json`. Packet features remain unavailable placeholders because no PCAP is present. CIC flow CSVs can populate only verified flow aggregates and cannot provide event chronology.\n")
    final_eval = {"status": "PARTIALLY_DONE", "dataset": evaluation["dataset"], "model": metadata, "split": evaluation["split_definition"], "metrics": evaluation["test_results"], "expanded_evaluation": {"eligible_episode_count": expanded["eligible_episode_count"], "forecast_cases": expanded["previous_24_pair_experiment"]["forecast_cases"], "aggregate_results": expanded["aggregate_results"]}, "comparison_conclusion": "The LSTM does not improve over persistence on the measured eligible episode; no improvement claim is justified.", "packet_features_available": False, "retraining_performed": False}
    write_json("world_model_final_evaluation.json", final_eval)
    write_md("world_model_final_evaluation.md", f"""# World Model Final Evaluation\n\n## Status\n\n**PARTIALLY_DONE**. Existing measurements are preserved; no retraining was performed.\n\n## Model\n\nNumPy LSTM, 46 inputs, hidden size 24, lookback 8, 60-second windows, recursive horizon 5, seed 7. Dataset: UNSW-NB15.\n\n## Measured Result\n\nThe eligible future evaluation contains one mixed-state episode and 24 forecast cases. LSTM: precision `{evaluation['test_results']['lstm']['precision']}`, recall `{evaluation['test_results']['lstm']['recall']}`, F1 `{evaluation['test_results']['lstm']['f1']}`, macro-F1 `{evaluation['test_results']['lstm']['macro_f1']}`, balanced accuracy `{evaluation['test_results']['lstm']['balanced_accuracy']}`, ROC-AUC `{evaluation['test_results']['lstm']['roc_auc']}`, PR-AUC `{evaluation['test_results']['lstm']['pr_auc']}`, coverage `{evaluation['test_results']['lstm']['coverage']}`, abstention rate `{evaluation['test_results']['lstm']['abstention_rate']}`.\n\nPersistence: precision `{evaluation['test_results']['temporal_persistence']['precision']}`, recall `{evaluation['test_results']['temporal_persistence']['recall']}`, F1 `{evaluation['test_results']['temporal_persistence']['f1']}`, macro-F1 `{evaluation['test_results']['temporal_persistence']['macro_f1']}`, balanced accuracy `{evaluation['test_results']['temporal_persistence']['balanced_accuracy']}`, coverage `{evaluation['test_results']['temporal_persistence']['coverage']}`.\n\n**Conclusion:** persistence outperforms the LSTM on this measured episode. This is not evidence of AI improvement or generalization.\n\nFull machine-readable details are in `world_model_final_evaluation.json`.\n""")
    manifest = {"generated_at_utc": now, "workspace": str(ROOT), "datasets": {"world_model": "UNSW-NB15", "flow_audit": "CIC-IDS2017 MachineLearningCVE"}, "model": {"package": "models/nexsolve_world_model", "format": config["model_format"], "architecture": config["architecture"], "seed": config["seed"], "window_seconds": config["window_seconds"], "lookback": config["lookback"], "forecast_horizon": config["forecast_horizon"], "feature_count": config["input_size"]}, "model_artifact_hashes": model_hashes, "cic_csv_hashes": cic_hashes, "preprocessing": "train-only scaler fit as documented in existing evaluation", "splits": evaluation["split_definition"], "code_version": "not available: workspace is not a git repository", "retraining": False}
    write_json("reproducibility_manifest.json", manifest)
    write_md("demo_scenario.md", f"""# Demo Scenario\n\n## Selected Scenario\n\n**UNSW-NB15 temporal research episode** is the strongest currently runnable demo because the active model was trained on UNSW and the dataset provides timestamps. Exact episode selection and evaluation are documented in `unsw_forecast_expanded_evaluation.json`.\n\nThe preferred Friday afternoon PortScan scenario is not selected: its CIC flow CSV has no event timestamps and no PCAP is present.\n\n## Demo Flow\n\n1. Use verified timestamped UNSW flow states.\n2. Validate the 46-feature state contract.\n3. Run the protected NumPy LSTM.\n4. Display current state, recursive T+1 through T+5, contextual progression, ATT&CK context, explanation, abstention, and limitations.\n\n## Limitations\n\nThis is a research prototype with one eligible mixed-state future episode, no packet observations, uncalibrated probabilities, and no production deployment claim.\n""")
    metrics = {"status": "PARTIALLY_DONE", "detection": {"source": "existing CIC Logistic Regression baseline", "comparability": "static detection only; not forecasting", "artifact": "results/detection_baseline.json"}, "forecasting": {"dataset": "UNSW-NB15", "model": "existing NumPy LSTM", "test_cases": evaluation["test_results"]["lstm"]["forecast_cases"], "evaluated_cases": evaluation["test_results"]["lstm"]["evaluated_cases"], "metrics": evaluation["test_results"]["lstm"]}, "persistence_baseline": evaluation["test_results"]["temporal_persistence"], "multi_horizon": {"status": "NOT_YET_SUPPORTED", "reason": "Existing reported evaluation is aggregate next-window scoring; horizon-specific T+1..T+5 metrics are not available."}, "calibration": {"status": "NOT_YET_SUPPORTED", "reason": "No sufficient independent validation evidence for calibration claim."}, "coverage": evaluation["test_results"]["lstm"]["coverage"], "abstention": evaluation["test_results"]["lstm"]["abstention_rate"], "data_quality": {"cic_files": flow_audit["files_audited"], "cic_rows": flow_audit["quality_report"]["total_rows"], "cic_valid_rows": flow_audit["quality_report"]["total_valid_rows"], "cic_malformed_rows": flow_audit["quality_report"]["total_malformed_rows"], "cic_timestamp_available": False}}
    write_json("final_metrics.json", metrics)
    write_md("final_metrics.md", "# Final Metrics\n\nOnly experimentally obtained values are included. Detection metrics are not mixed with next-window forecasting metrics.\n\n- Forecast dataset: UNSW-NB15\n- LSTM forecast cases: 24\n- Evaluated cases: 16\n- Coverage: 0.6666666666666666\n- Abstention rate: 0.3333333333333333\n- LSTM macro-F1: 0.5607843137254902\n- Persistence macro-F1: 0.9142857142857144\n- Conclusion: persistence outperformed the LSTM on the sole eligible mixed-state episode.\n- Horizon-specific T+1 through T+5 metrics: not available in existing evidence.\n- Calibration metrics: not available.\n")
    write_md("NEXSOLVE_FINAL_ARCHITECTURE.md", """# NexSolve Final Architecture\n\n## Research Data Flow\n\nINPUT\n↓\nFEATURE EXTRACTION\n↓\nNETWORK STATE\n↓\nWORLD MODEL\n↓\nFORECAST\n↓\nATTACK PROGRESSION\n↓\nMITRE ATT&CK CONTEXT\n↓\nEXPLANATION\n↓\nDEFENDER DECISION SUPPORT\n\n## Research Architecture\n\nThe current research path ingests timestamped UNSW flow records into deterministic 60-second states, encodes 18 flow, 22 packet-interface, and 6 temporal values, and uses a protected NumPy LSTM for recursive five-step forecasting. Packet values are unavailable placeholders until a PCAP is audited. The CIC flow adapter is deterministic and label-preserving but cannot establish event chronology.\n\n## Security Boundaries\n\nLabels are targets only. Future observations are excluded. The ATT&CK bundle is read-only context. Explanations use associated-with language and do not claim causality. Defender guidance is non-autonomous; the system does not block, isolate, terminate, delete, or alter firewall rules. Raw payloads are not stored.\n\n## Production Boundary\n\nThe production React/Vite and Node/Express repository was not modified. The research FastAPI service is local research infrastructure, not proof of production deployment.\n\n## Limitations\n\nNo PCAP, packet/flow alignment, CIC temporal training, calibrated uncertainty, broad multi-episode evaluation, or validated production end-to-end connection is available.\n""")
    write_md("SIH_CLAIM_AUDIT.md", """# SIH Technical Claim Audit\n\n| Claim | Status | Evidence and boundary |\n|---|---|---|\n| Network traffic ingestion | SUPPORTED | Local flow CSV ingestion and validation tests. |\n| Flow-level feature extraction | SUPPORTED | CIC adapter and UNSW state builder. |\n| Packet-level feature extraction | NOT_YET_SUPPORTED | No PCAP exists; no packet extraction performed. |\n| Temporal modeling | PARTIALLY_SUPPORTED | UNSW 60-second temporal states and chronological split; limited evaluation. |\n| Attack forecasting | PARTIALLY_SUPPORTED | One eligible mixed-state UNSW episode; LSTM below persistence. |\n| Multi-step forecasting | SUPPORTED | Existing recursive T+1 through T+5 implementation; performance by horizon unavailable. |\n| Attack progression | PARTIALLY_SUPPORTED | Contextual hypotheses only; no stage ground truth. |\n| MITRE ATT&CK mapping | PARTIALLY_SUPPORTED | T1046 validated from local STIX; contextual only, not observed technique ground truth. |\n| Explainability | PARTIALLY_SUPPORTED | Existing ablation association; no causal or SHAP/attention claim. |\n| Uncertainty | PARTIALLY_SUPPORTED | Margin-based confidence and abstention exist; calibration unavailable. |\n| Unseen-pattern generalization | NOT_YET_SUPPORTED | No adequate independent evidence. |\n| Proactive decision support | PARTIALLY_SUPPORTED | Non-autonomous recommendations exist; operational efficacy unvalidated. |\n\nUnsupported claims must not enter the SIH presentation.\n""")
    write_md("NEXSOLVE_FINAL_STATUS.md", """# NexSolve Final Status\n\n## DONE\n\n- Deterministic CIC flow audit and adapter.\n- Protected NumPy LSTM model package and recursive forecast contract.\n- Research intelligence layer with contextual stage and ATT&CK safeguards.\n- Local research service and automated tests.\n- Evidence-based reproducibility, claim, architecture, demo, metrics, and status reports.\n- Production backend typecheck, frontend lint/typecheck, and production ML tests passed without modifying production.\n\n## PARTIALLY_DONE\n\n- Temporal forecasting: implemented on UNSW, evaluated on one eligible mixed-state episode.\n- Multi-step rollout: implemented, but horizon-specific metrics are unavailable.\n- MITRE context: local T1046 validation only; contextual, not confirmed.\n- Uncertainty: deterministic confidence/abstention, not calibrated.\n- Production integration: optional boundary exists, but no validated end-to-end connection.\n- Production backend tests: 14 passed, 1 existing health-contract test failed because `FORECAST_ENGINE_URL` was unset and the configured adapter was unavailable.\n\n## BLOCKED\n\n- PCAP extraction and packet/flow alignment: no PCAP/PCAPNG is present.\n- CIC temporal training: no exact timestamp field in the eight flow CSVs.\n- SIH packet compliance: TTL, fragmentation, packet timing, payload distribution, retransmission, and packet scan signatures unavailable.\n- Production build commands were not run because they emit artifacts into the protected production repository.\n\n## NOT_JUSTIFIED\n\n- AI improvement over persistence.\n- Reliable general-purpose attack or MITRE technique prediction.\n- Unseen-pattern generalization.\n- Production readiness or autonomous response.\n\n## Protected Artifacts\n\nThe active `models/nexsolve_world_model/` package and trained NPZ weights were not overwritten. The production repository was not modified.\n""")


def load_model_json(name: str) -> dict:
    return json.loads((MODEL / name).read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()