import { Link } from 'react-router-dom'
import {
  AlertTriangle,
  FileCheck,
  HardDrive,
  Lock,
  Shield,
  ShieldCheck,
  Terminal,
  WifiOff,
} from 'lucide-react'
import { Panel } from '../components/Ui'

export function Security() {
  return (
    <div className="page-stack page-enter security-page">
      {/* Hero */}
      <section className="security-hero">
        <div className="security-hero-tag">
          <span className="provenance-pill live-pill">AIR-GAPPED READY</span>
          <span className="provenance-pill status-pill">ZERO-DATA-EXFILTRATION</span>
        </div>
        <h1 className="security-title">Security & Data Governance</h1>
        <p className="security-subtitle">
          NexSolve operates completely offline on local compute. No packets, payloads, metadata, or telemetry ever leave your perimeter.
        </p>
      </section>

      {/* Primary Guarantees Grid */}
      <div className="security-guarantees-grid">
        <Panel className="guarantee-card">
          <div className="guarantee-icon-wrap">
            <WifiOff size={22} className="text-accent" />
          </div>
          <h3 className="guarantee-title">100% Offline-First Architecture</h3>
          <p className="guarantee-desc">
            All parsing, feature extraction, LSTM inference, rollout simulation, and report compilation execute locally within your isolated environment. The software makes zero external telemetry pings, DNS lookups, or API phone-homes.
          </p>
          <div className="guarantee-badge">Zero outbound connections</div>
        </Panel>

        <Panel className="guarantee-card">
          <div className="guarantee-icon-wrap">
            <HardDrive size={22} className="text-accent" />
          </div>
          <h3 className="guarantee-title">Zero Payload Retention</h3>
          <p className="guarantee-desc">
            Uploaded packet captures are processed in-memory or in ephemeral local temp dirs. Raw payload bytes are strictly used for header inspection, TCP handshake state verification, and feature computation, then purged immediately upon completion.
          </p>
          <div className="guarantee-badge">No packet storage persistence</div>
        </Panel>

        <Panel className="guarantee-card">
          <div className="guarantee-icon-wrap">
            <ShieldCheck size={22} className="text-accent" />
          </div>
          <h3 className="guarantee-title">Scientific Zero-Fabrication Contract</h3>
          <p className="guarantee-desc">
            Unlike heuristic systems that fabricate synthetic features when telemetry is missing, NexSolve adheres to a strict zero-fabrication contract. The disputed <code>mean_tcp_rtt</code> feature is completely omitted rather than approximated.
          </p>
          <div className="guarantee-badge">Audited 45-dim canonical contract</div>
        </Panel>

        <Panel className="guarantee-card">
          <div className="guarantee-icon-wrap">
            <FileCheck size={22} className="text-accent" />
          </div>
          <h3 className="guarantee-title">Cryptographic Report Signing</h3>
          <p className="guarantee-desc">
            Every analytical dossier generated by NexSolve is stamped with SHA-256 digests of the source capture file, the window aggregation log, and the model weight checkpoint. Every forensic finding can be verified independently.
          </p>
          <div className="guarantee-badge">SHA-256 chain-of-custody</div>
        </Panel>
      </div>

      {/* Detailed Data Handling Table */}
      <Panel className="security-matrix-panel">
        <div className="panel-header-simple">
          <div>
            <span className="panel-eyebrow">TELEMETRY GOVERNANCE</span>
            <h2 className="panel-title">Data Ingestion vs Retention Matrix</h2>
          </div>
          <span className="provenance-pill reference-pill">COMPLIANCE GRADE</span>
        </div>

        <div className="security-table-wrap">
          <table className="security-table">
            <thead>
              <tr>
                <th>Data Category</th>
                <th>Processing Method</th>
                <th>Retention Policy</th>
                <th>Perimeter Boundary</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Raw Packet Bytes</strong></td>
                <td>Streaming parser (header inspection only)</td>
                <td>Zero retention; discarded after feature extraction</td>
                <td><span className="status-badge status-badge-ok">Local Memory Only</span></td>
              </tr>
              <tr>
                <td><strong>Payload Content</strong></td>
                <td>Examined only for layer classification</td>
                <td>Zero storage; never logged or serialized</td>
                <td><span className="status-badge status-badge-ok">Local Memory Only</span></td>
              </tr>
              <tr>
                <td><strong>IP / Port Identifiers</strong></td>
                <td>Hashed for 5-tuple flow aggregation</td>
                <td>Anonymized in exportable telemetry if desired</td>
                <td><span className="status-badge status-badge-ok">Local Node Boundary</span></td>
              </tr>
              <tr>
                <td><strong>45-Dim State Vectors</strong></td>
                <td>Continuous aggregation into 60s windows</td>
                <td>Ephemeral job storage; exported on user demand</td>
                <td><span className="status-badge status-badge-ok">Local Host File System</span></td>
              </tr>
              <tr>
                <td><strong>Forecast Weights</strong></td>
                <td>Pre-trained local NumPy / PyTorch weights</td>
                <td>Immutable read-only weight artifacts</td>
                <td><span className="status-badge status-badge-ok">Air-Gapped Local Model</span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </Panel>

      {/* Model Safety and Abstention Section */}
      <section className="safety-gates-section">
        <div className="section-heading-wrap">
          <span className="panel-eyebrow">SAFETY BY DESIGN</span>
          <h2 className="section-title">Calibrated Abstention & Guardrails</h2>
          <p className="section-desc">
            How NexSolve prevents false alarms and hallucinated attack trajectories when telemetry is degraded or unrepresentative.
          </p>
        </div>

        <div className="safety-cards-grid">
          <div className="safety-card">
            <div className="safety-card-top">
              <AlertTriangle size={18} className="text-warning" />
              <span className="safety-card-code">GATE-01</span>
            </div>
            <h4>Insufficient Lookback Window Abstention</h4>
            <p>
              The world model requires a minimum of 8 continuous 60-second observation windows (&ge; 480 seconds) to initialize the autoregressive hidden state. If a capture has fewer windows, the engine deliberately abstains rather than inventing prior context.
            </p>
          </div>

          <div className="safety-card">
            <div className="safety-card-top">
              <Lock size={18} className="text-warning" />
              <span className="safety-card-code">GATE-02</span>
            </div>
            <h4>Out-of-Distribution Feature Clamping</h4>
            <p>
              Features exceeding known physical bounds (e.g. negative packet sizes, non-monotonic timestamps, impossible inter-arrival rates) trigger validation warnings and are clamped to physical extrema with full audit annotations.
            </p>
          </div>

          <div className="safety-card">
            <div className="safety-card-top">
              <Shield size={18} className="text-warning" />
              <span className="safety-card-code">GATE-03</span>
            </div>
            <h4>Model Champion Governance</h4>
            <p>
              In strict adherence to scientific rigor, the Persistence Champion serves as our primary validated baseline. The deep neural LSTM45 candidate remains clearly demarcated under scientific review, preventing unwarranted claims of benchmark superiority.
            </p>
          </div>
        </div>
      </section>

      {/* Verification CTA */}
      <section className="security-cta-banner">
        <div className="cta-banner-text">
          <h3>Verify our security and offline operation</h3>
          <p>Run NexSolve in an isolated VM, inspect our open Python extractors, or analyze network egress during execution.</p>
        </div>
        <div className="cta-banner-btn">
          <Link to="/analyze" className="button button-primary">
            <Terminal size={14} /> Open Local Console
          </Link>
        </div>
      </section>
    </div>
  )
}
