import { Check, ExternalLink, Info, Server, Shield } from 'lucide-react'
import { ErrorState, LoadingState, Panel, SectionHeading, StatusPill } from '../components/Ui'
import { useProductionData } from '../hooks/useProductionData'

export function Settings() {
  const { data, loading, error, reload } = useProductionData()
  if (loading) return <LoadingState message="Checking system configuration" />
  if (error || !data) return <ErrorState message={error ?? 'No analysis has been loaded.'} onRetry={() => void reload()} />
  return <div className="page-stack page-enter"><SectionHeading eyebrow="Settings / System" title="System configuration" description="Operational context for the NexSolve demonstration environment." /><div className="content-grid"><Panel><SectionHeading title="Connection" /><div className="detail-list"><div><span><Server size={15} /> API status</span><StatusPill>Connected</StatusPill></div><div><span>Endpoint mode</span><strong>Local FastAPI</strong></div><div><span>Analysis ID</span><strong>{data.results.analysis_id}</strong></div><div><span>Service version</span><strong>{data.health.model_version}</strong></div></div></Panel><Panel><SectionHeading title="Application" /><div className="detail-list"><div><span>Product version</span><strong>0.1.0</strong></div><div><span>Active source</span><strong>{data.results.source?.name ?? 'CIC packet windows'}</strong></div><div><span>Source mode</span><strong>{data.results.source?.kind === 'uploaded_pcap' ? 'Temporary upload' : 'Read-only Parquet'}</strong></div><div><span>Forecast horizon</span><strong>{data.health.K} windows</strong></div></div></Panel></div><Panel><SectionHeading title="Method boundaries" /><div className="boundary-grid"><div className="boundary-card"><div className="boundary-icon"><Shield size={18} /></div><div><h3>Packet analysis</h3><p>Uses packet-window aggregates, traffic indicators, and transparent risk scoring. Findings are evidence-based heuristics.</p><span className="boundary-state"><Check size={14} /> Active</span></div></div><div className="boundary-card"><div className="boundary-icon muted"><Info size={18} /></div><div><h3>LSTM forecast model</h3><p>The existing research forecast service is separate. Packet-only production and uploaded data do not satisfy its flow-plus-temporal feature contract.</p><span className="boundary-state muted-text"><ExternalLink size={14} /> Research endpoint</span></div></div></div></Panel></div>
}
